### PR TITLE
Feature add styling to Leaderboard project

### PR DESCRIPTION
**Pull request by gitbygaurav**
## **On this feature branch, the below features have been implemented:-

- Improved the look and feel of the application by adding styling.
- Used plain CSS.

Thanks 😊

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @gauravgangwarweb , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Good project design.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly make sure that all the main headers from [this README template](https://github.com/microverseinc/readme-template) are present in your Repo. The only optional section is FAQ. Remember to have added the section **Future Features**, including 1-3 potential features to be added. Also remember to remove the template logo, optionally you can replace it with your own logo if you have one.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gitbygaurav** [comment]
Hi @muneebulrehman 

Thanks for the review.
But I think those changes should be optional suggestions.
Well, I have made those changes.😊

**Review by roshan-bajgain — APPROVED** [review]
Hi @gauravgangwarweb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions
- [ ] You have small issues so I am giving it an optional please implement it, your MIT license is broken please fix it

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gitbygaurav** [comment]
Hi @roshan-bajgain 

Thanks for your review 😊.

**Pull request merged**
